FileRepositoryWebApp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.loginView, name='index'),
    path('login/', views.loginView, name='loginView'),
    path('login/<int:error>', views.loginView, name='loginViewInvalid'),
    path('login/verification', views.login, name='login'),
    path('registration/', views.registerView, name='registerView'),
    path('registration/verification', views.register, name='register'),
    path('logout', views.logout, name='logout')
]

file_management/urls.py
from django.urls import path
from . import views

app_name = "file-management"
urlpatterns = [
    
    path('category/<int:category_id>/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>',
         views.index, name='filter1'),

    path('category/<int:category_id>/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>/search=<str:query>',
         views.index, name='filter2'),

    path('category/<int:category_id>/sort/<int:sort_by>/search=<str:query>',
         views.index, name='search'),

    path('success/<int:success>/', views.index, name='success'),
    
    path('archived/success/<int:success>/', views.archivedIndex, name='archived-success'),

    path('', views.index, name='index'),

    path('<int:isAdded>', views.index, name='index'),

    path('archived', views.archivedIndex, name='archived-index'),

    path('archived/category/<int:category_id>/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>',
         views.archivedIndex, name='archived-filter1'),
    
    path('archived/category/<int:category_id>/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>/search=<str:query>',
         views.archivedIndex, name='archived-filter2'),


    path('file/<int:file_id>/', views.detail, name='detail'),
    path('upload', views.openUploadView, name='openUploadView'),
    path('edit/<int:file_id>/', views.openEditView, name='openEditView'),
    path('archive/<int:file_id>/', views.archive, name='archive'),
    path('saveUpload', views.upload, name='upload'),
    path('updateFile/<int:file_id>/', views.update, name='update'),

    path('restore/<int:file_id>/', views.restore, name='restore'),
    path('download=<int:file_id>', views.download, name='download'),
    
    path('checkDuplicateName', views.checkDuplicateName, name='check_duplicate_name'),
    path('view/pdf/<int:file_id>/', views.pdf_view, name='pdf_view'),
    path('file/<int:file_id>/print', views.printIndivualFilePDF, name='printIndividualFile'),

    path('print/category/<int:category_id>/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>',
         views.printActivePDF, name='printFilter1'),
    path('print/category/<int:category_id>/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>/search=<str:query>',
         views.printActivePDF, name='printFilter2'),

    path('archived/print/category/<int:category_id>/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>',
         views.printArchivedPDF, name='printArchivedFilter1'),
    path('archived/print/category/<int:category_id>/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>/search=<str:query>',
         views.printArchivedPDF, name='printArchivedFilter2'),
]

file_repository_web_app/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import login
from accounts.views import register
from users_management.views import profile, UpdatePassword, DeleteAccount, UpdateAccountDetails, AddUserAccount, AddAccount, EditAccount, ViewAccount, ArchieveUserAccount, RestoreUserAccount, SaveChangesOnEditUserAccount, UploadProfilePicture
from category_management.views import categoryManagement, AddCategory, UpdateCategory, DeleteCategory, archiveCategory, RestoreCategory, UpdateArchivedCategory

from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('file-management/', include('file_management.urls')),
    path('activity-log/', include('activity_log.urls')),
    path('manage-accounts/', include('users_management.urls')),
    path('', include('accounts.urls')),
    path('profile/', profile, name='profile'),
    path('profile/image-uploaded', UploadProfilePicture, name='UploadProfilePicture'),
    path('profile/update-password', UpdatePassword, name='UpdatePassword'),
    path('profile/delete-account', DeleteAccount, name='DeleteAccount'),
    path('profile/update-account', UpdateAccountDetails, name='UpdateAccountDetails'),
    path('manage-accounts/archived-a-user', ArchieveUserAccount, name='ArchieveUserAccount'),
    path('manage-accounts/restore-a-user', RestoreUserAccount, name='RestoreUserAccount'),
    path('manage-accounts/add-a-user', AddUserAccount, name='AddUserAccount'),
    path('manage-accounts/Add', AddAccount, name='AddAccount'),
    path('manage-accounts/Add/success', SaveChangesOnEditUserAccount, name='SaveChangesOnEditUserAccount'),
    path('manage-accounts/Edit', EditAccount, name='EditAccount'),
    path('manage-accounts/View', ViewAccount, name='ViewAccount'),
    path('category/', categoryManagement, name='categoryManagement'),
    path('category/archive', archiveCategory, name='archiveCategory'),
    path('category/archive/restore', RestoreCategory, name='RestoreCategory'),
    path('category/archive/update', UpdateArchivedCategory, name='UpdateArchivedCategory'),
    path('category/add', AddCategory, name='AddCategory'),
    path('category/update', UpdateCategory, name='UpdateCategory'),
    path('category/delete', DeleteCategory, name='DeleteCategory')]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

file_management/views.py
import datetime
# Import mimetypes module
import mimetypes
# import os module
import os
from io import BytesIO

from activity_log.models import Log
from category_management.models import Category
from django.core.exceptions import PermissionDenied
from django.core.files import File as DjangoFile
from django.db.models import Q
from django.http import (FileResponse, Http404, HttpResponse,
                         HttpResponseRedirect)
# Import HttpResponse module
from django.http.response import HttpResponse
# Import render module
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)
from users_management.models import User

from .models import File


def index(request,  category_id=0, sort_by=4, query=None, fromDate=None, toDate=None, success = 0):

    try:
        session_user_id = request.session.get('user_id')
        logged_user = User.objects.get(pk=session_user_id)
    except:
        return HttpResponseRedirect(reverse('index'))
    
    template_name = 'file_management/index.html'

    if query == None: query = ""
    sort_column = "name"

    if (sort_by == 2):
        sort_column = "category_id__title"
    elif (sort_by == 3):
        sort_column = "user_id__first_name"
    elif (sort_by == 4):
        sort_column = "-created_at"
    elif (sort_by == 5):
        sort_column = "created_at"

    if fromDate == None:
        try:
            FromDate = File.objects.order_by('id').first().created_at
            fromDate = FromDate.strftime("%Y-%m-%d")
        except:
            FromDate = datetime.date.today()
            fromDate = FromDate.strftime("%Y-%m-%d")

        ToDate = datetime.date.today()
        toDate = ToDate.strftime("%Y-%m-%d")

    if (category_id > 0):
        date1 = datetime.datetime.strptime(fromDate, "%Y-%m-%d").date()
        date2 = datetime.datetime.strptime(
            toDate, "%Y-%m-%d").date() + datetime.timedelta(days=1)

        file_list = File.objects.filter(
            Q(name__icontains=query) |
            Q(url__endswith=query) |
            Q(category_id__title__icontains=query) |
            Q(user_id__first_name__icontains=query) |
            Q(user_id__last_name__icontains=query) |
            Q(user_id__created_at__icontains=query),
            created_at__gte=date1,
            created_at__lte=date2,
            category_id=category_id, deleted_at=None
        ).order_by(sort_column)

    else:
        date1 = datetime.datetime.strptime(fromDate, "%Y-%m-%d").date()
        date2 = datetime.datetime.strptime(toDate, "%Y-%m-%d").date() + datetime.timedelta(days=1)

        file_list = File.objects.filter(
            Q(name__icontains=query) |
            Q(url__endswith=query) |
            Q(category_id__title__icontains=query) |
            Q(user_id__first_name__icontains=query) |
            Q(user_id__last_name__icontains=query) |
            Q(user_id__created_at__icontains=query),
            created_at__gte=date1,
            created_at__lte=date2,
            deleted_at=None
        ).order_by(sort_column)

    return render(request, template_name, 
    {"file_list": file_list,
     "category_selected" : category_id,
     "sort_selected": sort_by,
     "search_value": query,
     "from_date": fromDate,
     "to_date": toDate,
     "success": success,
     "user" : logged_user,
     "category_list": Category.objects.filter(isArchived = False)})

def detail(request, file_id):

    try:
        session_user_id = request.session.get('user_id')
        logged_user = User.objects.get(pk=session_user_id)
    except:
        return HttpResponseRedirect(reverse('index'))

    template_name = 'file_management/detail.html'
    file = get_object_or_404(File, pk=file_id)
    return render(request, template_name, {"file": file, "user" : logged_user})


def archivedIndex(request,  category_id=0, sort_by=4, query=None, fromDate=None, toDate=None, success=0):

    try:
        session_user_id = request.session.get('user_id')
        logged_user = User.objects.get(pk=session_user_id)
    except:
        return HttpResponseRedirect(reverse('index'))

    template_name = 'file_management/archive.html'

    if query == None: query = ""
    sort_column = "name"

    if (sort_by == 2):
        sort_column = "category_id__title"
    elif (sort_by == 3):
        sort_column = "user_id__first_name"
    elif (sort_by == 4):
        sort_column = "-deleted_at"
    elif (sort_by == 5):
        sort_column = "deleted_at"

    if fromDate == None:

        try:
            FromDate = File.objects.order_by('id').first().created_at
            fromDate = FromDate.strftime("%Y-%m-%d")
        except:
            FromDate = datetime.date.today()
            fromDate = FromDate.strftime("%Y-%m-%d")

        ToDate = datetime.date.today()
        toDate = ToDate.strftime("%Y-%m-%d")

    if (category_id > 0):
        date1 = datetime.datetime.strptime(fromDate, "%Y-%m-%d").date()
        date2 = datetime.datetime.strptime(
            toDate, "%Y-%m-%d").date() + datetime.timedelta(days=1)

        file_list = File.objects.filter(
            Q(name__icontains=query) |
            Q(url__endswith=query) |
            Q(category_id__title__icontains=query) |
            Q(user_id__first_name__icontains=query) |
            Q(user_id__last_name__icontains=query) |
            Q(user_id__created_at__icontains=query),
            ~Q(deleted_at=None),
            deleted_at__gte=date1,
            deleted_at__lte=date2,
            category_id=category_id
        ).order_by(sort_column)

    else:
        date1 = datetime.datetime.strptime(fromDate, "%Y-%m-%d").date()
        date2 = datetime.datetime.strptime(toDate, "%Y-%m-%d").date() + datetime.timedelta(days=1)

        file_list = File.objects.filter(
            Q(name__icontains=query) |
            Q(url__endswith=query) |
            Q(category_id__title__icontains=query) |
            Q(user_id__first_name__icontains=query) |
            Q(user_id__last_name__icontains=query) |
            Q(user_id__created_at__icontains=query),
            ~Q(deleted_at=None),
            deleted_at__gte=date1,
            deleted_at__lte=date2
        ).order_by(sort_column)

    return render(request, template_name, 
    {"file_list": file_list,
     "category_selected" : category_id,
     "sort_selected": sort_by,
     "search_value": query,
     "from_date": fromDate,
     "to_date": toDate,
     "success": success,
     "user" : logged_user,
     "category_list": Category.objects.filter(isArchived = False)})


def openUploadView(request):

    try:
        session_user_id = request.session.get('user_id')
        logged_user = User.objects.get(pk=session_user_id)
    except:
        return HttpResponseRedirect(reverse('index'))

    return render(request, 'file_management/upload.html', 
    {"category_list": Category.objects.filter(isArchived = False),
    "user" : logged_user,
    "error" : 0})

def upload(request):

    try:
        session_user_id = request.session.get('user_id')
        logged_user = User.objects.get(pk=session_user_id)
    except:
        return HttpResponseRedirect(reverse('index'))

    name = request.POST['name']
    description = request.POST['description']
    category_id = Category.objects.get(pk=request.POST['category_id'])
    user_id = User.objects.get(pk=session_user_id)

    file = File()
    file.name = name
    file.description = description
    file.category_id = category_id
    file.user_id = user_id
    file.url = request.FILES['file']

    try:
        file.save()

        log = Log()
        log.description = f"Uploaded a file ({file.id} - {file.name}) under {file.category_id.title}."
        log.user_id = user_id
        log.save()

        return HttpResponseRedirect(reverse('file-management:success', args={1}))
    except:
        return render(request, 'file_management/upload.html',
            {"category_list": Category.objects.filter(isArchived = False),
            "file" : file,
            "error": 1,
            "user" : logged_user})  # 2 means general error

def openEditView(request, file_id):

    try:
        session_user_id = request.session.get('user_id')
        logged_user = User.objects.get(pk=session_user_id)
    except:
        return HttpResponseRedirect(reverse('index'))

    file = get_object_or_404(File, pk=file_id)
    return render(request, 'file_management/edit.html', 
        {"category_list": Category.objects.filter(isArchived = False), 
         "file": file,
         "error": 0,
         "user" : logged_user})

def update(request, file_id):


    try:
        session_user_id = request.session.get('user_id')
        logged_user = User.objects.get(pk=session_user_id)
    except:
        return HttpResponseRedirect(reverse('index'))

    name = request.POST['name']
    description = request.POST['description']
    category_id = Category.objects.get(pk=request.POST['category_id'])
    user_id = User.objects.get(pk=session_user_id)

    file = File.objects.get(pk=file_id)
    file.name = name
    file.description = description
    file.category_id = category_id
    file.user_id = user_id

    try:
        file.url = request.FILES['file']
    except:
        pass
    try:
        file.save()
        log = Log()
        log.description = f"Updated a file ({file.id} - {file.name}) under {file.category_id.title}."
        log.user_id = user_id
        log.save()
        return HttpResponseRedirect(reverse('file-management:success', args={2}))
    except:
        return render(request, 'file_management/upload.html',
                      {"category_list": Category.objects.filter(isArchived = False),
                       "file": file,

file_management/templates/file_management/detail.html
{% extends 'file_management/base.html' %}

{% block content %}
<div style="display: flex; align-items: flex-start; justify-content: space-between; gap: 1rem;">
    <h1 class="h1">Viewing a File</h1>
    <div style="display: flex; align-items: flex-start; justify-content: space-between; gap: 1rem; margin-top: 12.5px">
        <a href="{% url 'file-management:openEditView' file.id %}"><button title="Edit"
                style="border: none; background-color:transparent; cursor: pointer;"><svg width="20"
                height="20" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M0.25 10.9375V13.75H3.0625L11.3575 5.45504L8.545 2.64254L0.25 10.9375ZM13.5325 3.28004C13.825 2.98754 13.825 2.51504 13.5325 2.22254L11.7775 0.467544C11.485 0.175044 11.0125 0.175044 10.72 0.467544L9.3475 1.84004L12.16 4.65254L13.5325 3.28004Z"
                    fill="#272727" fill-opacity="0.5"></path>
            </svg></button></a>
            <button id="archive" title=" archive" data-fileid={{file.id}} data-filename="{{file.getNewFileName}}"
                style="border: none; background-color:transparent; cursor: pointer;"><svg width="20"
                height="20" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M13.405 1.9225L12.3625 0.6625C12.16 0.4075 11.8525 0.25 11.5 0.25H2.5C2.1475 0.25 1.84 0.4075 1.63 0.6625L0.595 1.9225C0.3775 2.1775 0.25 2.515 0.25 2.875V12.25C0.25 13.075 0.925 13.75 1.75 13.75H12.25C13.075 13.75 13.75 13.075 13.75 12.25V2.875C13.75 2.515 13.6225 2.1775 13.405 1.9225ZM7 11.125L2.875 7H5.5V5.5H8.5V7H11.125L7 11.125ZM1.84 1.75L2.4475 1H11.4475L12.1525 1.75H1.84Z"
                    fill="#272727" fill-opacity="0.5"></path>
            </svg></button>
    </div>
</div>
<section class="viewing-file">
    <div class="viewing-file-container">

        <div class="flex-head mb-2">
            <div>
                <h4>{{file.getNewFileName}}</h4>
                <small>{{ file.getSize }}</small>
            </div>
            <div class="btn-dark">
                <a href="{% url 'file-management:download' file.id %}"><span class="iconify"
                        data-icon="ic:baseline-download"></span>Download File</a>
            </div>
        </div>

        <div class="flex-head mb-1">
            <div>
                <div class="flex spacing mb-1">
                    <h4>Category: </h4>
                    <div>
                        <p>{{file.category_id.title}}</p>
                    </div>
                </div>
                <div class="flex spacing mb-1">
                    <h4>Uploader:</h4>
                    <div class="content">
                        <p>{{file.user_id.full_name}}</p>
                    </div>
                </div>
            </div>
            <div>
                <div class="flex spacing mb-1">
                    <h4>Uploaded: </h4>
                    <div>
                        <p>{{file.created_at}}</p>
                    </div>
                </div>
                <div class="flex spacing mb-1">
                    <h4>Modified:</h4>
                    <div>
                        <p>{{file.updated_at}}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="flex-description spacing mb-2">
            <h4>Description:</h4>
            <div>{% if file.description %}
                <p>{{file.description}}</p>
                {% else %}
                <p>No additional details are provided for this file.</p>
                {% endif %}
            </div>
        </div>

        <div class="preview">
            {% if file.getFileType == 1 %}
            <image src='{{file.url.url}}' style="max-width: 800px;max-height:500px; width:auto; height:auto"></iframe>
            {% elif file.getFileType == 2  %}
            <video controls src="{{file.url.url}}" style="width:100%; height:500px">
                <p onclick='downloadFile()'>Your browser does not support HTML5 Element. You may download this file
                        instead.</p>
            </video>
            {% elif file.getFileType == 3  %}
            <iframe src='{{file.url.url}}' width='100%' height='500px' frameborder='0'
                    style="background:white"></iframe>
            {% else %}
            <p style="text-align: center" onclick='downloadFile()'>Sorry, but we cannot display your file, click
                    this to download instead.</p>
                {% endif %}
        </div>

        {% if user.is_superuser == True %}
        <div class="btn-dark" style="margin-top: 30px">
            <a href="{% url 'file-management:printIndividualFile' file.id %}"><span class="iconify"
                    data-icon="akar-icons:paper"></span>Print details to PDF</a>
        </div>
        {% endif %}
    </div>
    <script>

        function downloadFile() {
            var link = "{% url 'file-management:download' 0 %}".replace("0", {{file.id}})
            window.open(link);
        }

        
      $(document).on('click', '#archive', function() {
             
         var file_name = $(this).data("filename");
         var file_id = $(this).data("fileid");

         Swal.fire({
            icon: 'warning',
            title: 'Do you want to archive ' + file_name +'?',
            showDenyButton: true,
            confirmButtonText: 'Yes, archive',
            denyButtonText: `Cancel`,
            }).then((result) => {
            if (result.isConfirmed) {
               var location = "{% url 'file-management:archive' 0 %}".replace(0, file_id);
               window.location.href = location;
            } else if (result.isDenied) {

            }
            });
      });
          
    </script>
</section>
{% endblock %}

file_management/templates/file_management/edit.html
{% extends 'file_management/base.html' %}

{% block content %}
<section class="file-management">
   <div class="file-management--container">
      <h1 class="h1">Editing a File</h1>
  
      <form id="my_form" method="POST" action="{% url 'file-management:update' file.id %}" enctype="multipart/form-data">
         {% csrf_token %}
         <div class="container">
            <div class="column">
               <h4>You may change your uploaded file, but the maximum size is still only at 500mb.</h4>
            </div>
            <div class="columns">
               <div class="column">
                  <input id="name" class="input" type="text" placeholder="Enter a file name" name="name" value="{{ file.name }}" maxlength="30">
               </div>
               <div class="column column-file" style="position: relative">
                  <div class="icon-file-upload">
                     <svg width="22" height="15" viewBox="0 0 22 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M17.7375 5.6625C17.1142 2.42812 14.3367 0 11 0C8.35083 0 6.05 1.5375 4.90417 3.7875C2.145 4.0875 0 6.47813 0 9.375C0 12.4781 2.46583 15 5.5 15H17.4167C19.9467 15 22 12.9 22 10.3125C22 7.8375 20.1208 5.83125 17.7375 5.6625ZM12.8333 8.4375V12.1875H9.16667V8.4375H6.41667L10.6792 4.07813C10.8625 3.89063 11.1467 3.89063 11.33 4.07813L15.5833 8.4375H12.8333Z" fill="#8761F4"/>
                        </svg>
                  </div>
                 <div class="column--inner">
                  <input id="file" class="input" type="file" placeholder="Text input" name="file" style="color:white">
                  <input id="file-value" value="{{file.url.url}}" name="file_temp" hidden>
                  {% comment %} <input type="file" name="uploadfile" id="img" style="display:none;"/> {% endcomment %}
                  <label for="file" id="file-value-placeholder" style="position: absolute; display: block;">
                     {% if file%}
                        {{file.url}}
                     {% else %}
                     You haven't selected a file yet
                     {%endif%}
                  </label>
                 </div>
               </div>
            </div>

            <div class="columns">
               <div class="column column-dropdwon">
                  <select name="category_id" id="category" style="color: #272727;" >
                     {% if category_list %}
                     {% for category in category_list %}
                     <option value="{{category.id}}" {% if file.category_id.id == category.id %} selected {%endif%} >{{category.title}}</option>
                     {% endfor %}
                     {% else %}
                     <option value="0">No categories yet</option></a>
                     {% endif %}
                  </select>
               </div>
            </div>
            <div class="columns">
               <div class="column">
                  <textarea class="textarea" placeholder="Enter details of the file uploaded (Optional)"
                     name="description" maxlength="500">{{ file.description }}</textarea>
               </div>
            </div>
            <div class="columns">
               <div class="column column-btn">
                  <a href="{%url 'file-management:index' %}"><button class="btn-black" type="button">Cancel</button></a>
                  <button class="btn-black" type="submit">Update file</button>
               </div>
            </div>
         </div>
      </form>
   </div>
</section>


<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>

     //Check for special Characters(kenet)
   
// $("#name").keypress(function(event) {
//    var character = String.fromCharCode(event.keyCode);
//    if(! isValid(character)){
//       Swal.fire({
//          icon: 'error',
//          title: "File name could not contain special characters.",
//          confirmButtonText: 'Ok',
//       })
//    }
//    return isValid(character);
// });
//    function isValid(str) {
//          return !/[~`!@#$%\^&*()+=\-\[\]\\';,/{}|\\":<>\?]/g.test(str);
//      }

   var beingSubmitted = false;

   $(document).ready(function () {

      var alreadyPrompted = false;
      var error_msg = {{ error }};
      if (alreadyPrompted == false) {  
         if (error_msg == 1) {
            Swal.fire({
               icon: 'error',
               title: "An error has been encounter while uploading your file, please try again later."
            });
         }
      }
      
      $("#file").change(function(e){
         $("#file-value-placeholder").html(this.value.replace("C:\\fakepath\\", ""));
      });

      $("#my_form").submit(function(e){

         
         if (beingSubmitted) {
            return true;
         }
         
         var name = $("#name").val();
         var file_length = $("#file").get(0).files.length;
         var file_temp = $("#file_temp").val()
         var category = $("#category").val();

         if (name.trim() == "") {
            Swal.fire({
               icon: 'error',
               title: "Please enter a valid file name."
            })
         }
         else if (file_length == 0 && file_temp == "") {
            Swal.fire({
               icon: 'error',
               title: "Ooops, you forgot to select a file!"
            })
         } else if (file_length != 0) { 
               var file_size = $("#file").get(0).files[0].size;
               if (file_size > 524288000) {
                  Swal.fire({
                     icon: 'error',
                     title: "Your file is too big, please no more than 500mb!"
                  });

                  return false;
               } else {
            checkForDuplicatedNameThenSubmit();
               }
         } else if (category == "0") {
            Swal.fire({
               icon: 'error',
               title: "Please select a valid category."
            })
         } else {
            checkForDuplicatedNameThenSubmit();
         }

         return false;
      });
   });

   function checkForDuplicatedNameThenSubmit() {
      
               $.get(
                  "{%url 'file-management:check_duplicate_name'%}",
                  {name: $("#name").val(),
                   file_id: {{file.id}}}, 
                  function(data, status) {
                     if (data == 1) {
                        Swal.fire({
                           title: "That file name is already in used.",
                           button: false
                        });
                     } else {
                           $("#my_form").submit();
                           beingSubmitted = true;
                     }
                  }
               );
   }

</script>

{% endblock %}