FileRepositoryWebApp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.loginView, name='index'),
    path('login/', views.loginView, name='loginView'),
    path('login/<int:error>', views.loginView, name='loginViewInvalid'),
    path('login/verification', views.login, name='login'),
    path('registration/', views.registerView, name='registerView'),
    path('registration/verification', views.register, name='register'),
    path('logout', views.logout, name='logout')
]

activity_log/urls.py
from django.urls import path
from . import views

app_name = "activity-log"
urlpatterns = [
    path('', views.index, name='index'),

    path('sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>',
         views.index, name='filter1'),

    path('sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>/search=<str:query>',
         views.index, name='filter2'),

    path('print/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>',
         views.printPDF, name='printFilter1'),

    path('print/sort/<int:sort_by>/from/<str:fromDate>/to/<str:toDate>/search=<str:query>',
         views.printPDF, name='printFilter2'),
]

file_repository_web_app/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import login
from accounts.views import register
from users_management.views import profile, UpdatePassword, DeleteAccount, UpdateAccountDetails, AddUserAccount, AddAccount, EditAccount, ViewAccount, ArchieveUserAccount, RestoreUserAccount, SaveChangesOnEditUserAccount, UploadProfilePicture
from category_management.views import categoryManagement, AddCategory, UpdateCategory, DeleteCategory, archiveCategory, RestoreCategory, UpdateArchivedCategory

from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('file-management/', include('file_management.urls')),
    path('activity-log/', include('activity_log.urls')),
    path('manage-accounts/', include('users_management.urls')),
    path('', include('accounts.urls')),
    path('profile/', profile, name='profile'),
    path('profile/image-uploaded', UploadProfilePicture, name='UploadProfilePicture'),
    path('profile/update-password', UpdatePassword, name='UpdatePassword'),
    path('profile/delete-account', DeleteAccount, name='DeleteAccount'),
    path('profile/update-account', UpdateAccountDetails, name='UpdateAccountDetails'),
    path('manage-accounts/archived-a-user', ArchieveUserAccount, name='ArchieveUserAccount'),
    path('manage-accounts/restore-a-user', RestoreUserAccount, name='RestoreUserAccount'),
    path('manage-accounts/add-a-user', AddUserAccount, name='AddUserAccount'),
    path('manage-accounts/Add', AddAccount, name='AddAccount'),
    path('manage-accounts/Add/success', SaveChangesOnEditUserAccount, name='SaveChangesOnEditUserAccount'),
    path('manage-accounts/Edit', EditAccount, name='EditAccount'),
    path('manage-accounts/View', ViewAccount, name='ViewAccount'),
    path('category/', categoryManagement, name='categoryManagement'),
    path('category/archive', archiveCategory, name='archiveCategory'),
    path('category/archive/restore', RestoreCategory, name='RestoreCategory'),
    path('category/archive/update', UpdateArchivedCategory, name='UpdateArchivedCategory'),
    path('category/add', AddCategory, name='AddCategory'),
    path('category/update', UpdateCategory, name='UpdateCategory'),
    path('category/delete', DeleteCategory, name='DeleteCategory')]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

activity_log/models.py
from django.db import models
from users_management.models import User

class Log(models.Model):
    description = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

activity_log/views.py
from ctypes import alignment
from django.shortcuts import render
from datetime import datetime
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from users_management.models import User
from reportlab.platypus import Paragraph, Spacer
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import TableStyle
from reportlab.platypus import Table
from reportlab.lib import colors
from .models import User
from django.utils import timezone
from activity_log.models import Log
from django.db.models import Q
import datetime
from io import BytesIO
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from reportlab.lib.units import mm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from report_generation.views import PageNumCanvas
from reportlab.platypus import Image
from reportlab.pdfgen import canvas
import datetime
from reportlab.lib.units import inch

from tkinter import CENTER, Image
from tkinter.ttk import Style
from tkinter import CENTER
from django.shortcuts import render
from datetime import datetime
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from users_management.models import User
from reportlab.platypus import Paragraph, Spacer, Image
from reportlab.lib.units import cm, inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate
from reportlab.platypus import TableStyle
from reportlab.platypus import Table
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from .models import User
from django.utils import timezone
from activity_log.models import Log
import PIL.Image
from reportlab.rl_config import defaultPageSize
from django.db.models import Q
from io import BytesIO

from reportlab.lib.units import mm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import datetime

from reportlab.lib.enums import TA_LEFT, TA_CENTER
# ERIKA
def index(request,  sort_by=4, query=None, fromDate=None, toDate=None):

    try:
        session_user_id = request.session.get('user_id')
        logged_user = User.objects.get(pk=session_user_id)
        if logged_user.is_superuser == 0:
            return HttpResponseRedirect(reverse('index'))
    except:
        return HttpResponseRedirect(reverse('index'))
    
    template_name = 'activity_log/logs.html'

    if query == None:
        query = ""

    sort_column = "id"

    if (sort_by == 2):
        sort_column = "user_id__first_name"
    elif (sort_by == 3):
        sort_column = "description"
    elif (sort_by == 4):
        sort_column = "-created_at"
    elif (sort_by == 5):
        sort_column = "created_at"

    if fromDate == None:
        try:
            FromDate = Log.objects.order_by('id').first().created_at
            fromDate = FromDate.strftime("%Y-%m-%d")
        except:
            FromDate = datetime.date.today()
            fromDate = FromDate.strftime("%Y-%m-%d")

        ToDate = datetime.date.today()
        toDate = ToDate.strftime("%Y-%m-%d")

    date1 = datetime.datetime.strptime(fromDate, "%Y-%m-%d").date()
    date2 = datetime.datetime.strptime(
        toDate, "%Y-%m-%d").date() + datetime.timedelta(days=1)

    log_list = Log.objects.filter(
        Q(id__icontains=query) |
        Q(description__icontains=query) |
        Q(user_id__first_name__icontains=query) |
        Q(user_id__last_name__icontains=query) |
        Q(created_at__icontains=query),
        created_at__gte=date1,
        created_at__lte=date2
    ).order_by(sort_column)

    return render(request, template_name,
                  {"log_list": log_list,
                  "user" : logged_user,
                   "sort_selected": sort_by,
                   "search_value": query,
                   "from_date": fromDate,
                   "to_date": toDate})

def printPDF(request,  sort_by=4, query=None, fromDate=None, toDate=None):

    try:
        session_user_id = request.session.get('user_id')
        logged_user = User.objects.get(pk=session_user_id)
        if logged_user.is_superuser == 0:
            return HttpResponseRedirect(reverse('index'))
    except:
        return HttpResponseRedirect(reverse('index'))



    log = Log()
    log.description = f"A printed PDF report of the activity logs was generated."
    log.user_id = logged_user
    log.save()

    if query == None:
        query = ""

    sort_column = "id"

    if (sort_by == 2):
        sort_column = "user_id__first_name"
    elif (sort_by == 3):
        sort_column = "description"
    elif (sort_by == 4):
        sort_column = "-created_at"
    elif (sort_by == 5):
        sort_column = "created_at"

    if fromDate == None:
        try:
            FromDate = Log.objects.order_by('id').first().created_at
            fromDate = FromDate.strftime("%Y-%m-%d")
        except:
            FromDate = datetime.date.today()
            fromDate = FromDate.strftime("%Y-%m-%d")

        ToDate = datetime.date.today()
        toDate = ToDate.strftime("%Y-%m-%d")

    date1 = datetime.datetime.strptime(fromDate, "%Y-%m-%d").date()
    date2 = datetime.datetime.strptime(
        toDate, "%Y-%m-%d").date() + datetime.timedelta(days=1)

    log_list = Log.objects.filter(
        Q(id__icontains=query) |
        Q(description__icontains=query) |
        Q(user_id__first_name__icontains=query) |
        Q(user_id__last_name__icontains=query) |
        Q(created_at__icontains=query),
        created_at__gte=date1,
        created_at__lte=date2
    ).order_by(sort_column)

    response = HttpResponse(content_type='application/pdf')
    pdf_name = "logs-%s.pdf" % str(
        datetime.datetime.today().strftime('%Y-%m-%d-%H-%M-%S'))
    response['Content-Disposition'] = 'attachment; filename=%s' % pdf_name

    buff = BytesIO()
    paragraphStyle = getSampleStyleSheet()

    data = [
        ['Log ID', 'User', 'Description', 'Date Created']
    ]

    for log in log_list:
        created_at = log.created_at.strftime("%m/%d/%Y %I:%M %p")
        list = [Paragraph(f"{log.id}", paragraphStyle['Normal']),
                Paragraph(f"{log.user_id.full_name()}", paragraphStyle['Normal']),
                Paragraph(f"{log.description}", paragraphStyle['Normal']),
                Paragraph(f"{created_at}",  paragraphStyle['Normal'])]
        data.append(list)

    pdf = SimpleDocTemplate(
        buff,
        pagesize=letter,
        rightMargin=70,
        leftMargin=70, topMargin=50, bottomMargin=70
    )

    table = Table(data, colWidths=[
                  15 * mm, 40 * mm, 70 * mm, 40 * mm])

    style = TableStyle([
        ('BACKGROUND', (0, 0), (5, 0), colors.HexColor("#8761F4")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6)
    ])

    table.setStyle(style)

    rowNumber = len(data)
    for i in range(1, rowNumber):
        if i % 2 == 0:
            bc = colors.white
        else:
            bc = colors.HexColor("#DDDDDD")
        ts = TableStyle(
            [('BACKGROUND', (0, i), (-1, i), bc)]
        )
        table.setStyle(ts)

    borderStyle = TableStyle([
        ('BOX', (0, 0), (-1, -1), .5, colors.HexColor("#777777")),
        ('GRID', (0, 1), (-1, -1), .5, colors.HexColor("#777777"))
    ])

    title = "Activity Log"
    description = "The following are the activity logs for Soar Academy's English High School Department common drive."
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Subtitle',
                                  fontSize=12,
                                  leading=14,
                                  spaceAfter=6),
                   alias='subtitle')
    styles.add(ParagraphStyle(name='DefaultHeading',
                                  fontSize=18,
                                  leading=22,
                                  spaceBefore=12,
                                  spaceAfter=6),
                   alias='dh')    

    table.setStyle(borderStyle)

    elems = []
    elems.append(Image('reports/logo_header.jpg',width = 6.5 * inch, height = 0.885 * inch))
    elems.append(Spacer(.25 * cm, .25 * cm))
    elems.append(Paragraph(title, styles['DefaultHeading']))
    elems.append(Paragraph(description, styles['Subtitle']))
    elems.append(Spacer(.25 * cm, .25 * cm))
    elems.append(table)
    elems.append(Spacer(1 * cm, 1 * cm))

    pdf.build(elems, canvasmaker=PageNumCanvas)

    response.write(buff.getvalue())
    buff.close()
    return response

activity_log/templates/activity_log/logs.html
{% extends 'activity_log/base.html' %}

{% block content %}
<h1 class="h1">Activity Logs</h1>
<section class="activity-logs">
<div class="activity-logs--container">
   
      <div class="activity-logs--controls">
         <div class="activity-logs--controls-date" style="display: flex; gap: 1.4rem; align-items: flex-end;">
            <div>
               <p class="text-black text-small">Sort by</p>
               <div class="component4">
                  <select id="select-sort">
                     <option value=1 {% if sort_selected == 1 %} selected {%endif%}>Log ID</option>
                     <option value=2 {% if sort_selected == 2 %} selected {%endif%}>User</option>
                     <option value=3 {% if sort_selected == 3 %} selected {%endif%}>Description</option>
                     <option value=4 {% if sort_selected == 4 %} selected {%endif%}>Recently Created</option>
                     <option value=5 {% if sort_selected == 5 %} selected {%endif%}>Earliest Created</option>
                  </select>
               </div>
            </div>
           <div>
            <p class="text-small fw-600">Date created</p>
            <div class="component2">
               <div class="start-date">
                  <input type="text" id="datepicker-start" readonly value="{{from_date}}">
               </div>
               -
               <div class="end-date end-date-disabled">
                  <input type="text" id="datepicker-end" readonly disabled value="{{to_date}}" placeholder="To Date">
               </div>
               <style>
                  input:disabled{
                     cursor: not-allowed;
                  }
               </style>
            </div>
           </div>
         </div>
         <div class="activity-logs--controls-right">
            <div class="component3">
                  <div class="icon">
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                     <path d="M10.9167 9.66667H10.2583L10.025 9.44167C10.8417 8.49167 11.3333 7.25833 11.3333 5.91667C11.3333 2.925 8.90833 0.5 5.91667 0.5C2.925 0.5 0.5 2.925 0.5 5.91667C0.5 8.90833 2.925 11.3333 5.91667 11.3333C7.25833 11.3333 8.49167 10.8417 9.44167 10.025L9.66667 10.2583V10.9167L13.8333 15.075L15.075 13.8333L10.9167 9.66667ZM5.91667 9.66667C3.84167 9.66667 2.16667 7.99167 2.16667 5.91667C2.16667 3.84167 3.84167 2.16667 5.91667 2.16667C7.99167 2.16667 9.66667 3.84167 9.66667 5.91667C9.66667 7.99167 7.99167 9.66667 5.91667 9.66667Z" fill="#AAAAAA"/>
                     </svg>
                  </div>
               <input id="search" type="text" class="search-input" placeholder="Search" value="{{search_value}}">
            </div>
         </div>
      </div>

   <div class="activity-logs--table-container">
      {% if log_list %}
      <table>
         <thead>
            <tr>
               <th scope="col">Log ID</th>
               <th scope="col">User</th>
               <th scope="col">Description</th>
               <th scope="col">Date Created</th>
            </tr>
         </thead>
         <tbody>
            {% for log in log_list %}
            <tr>
               <td data-label="Log ID">{{log.id}}</td>
               <td data-label="User">{{log.user_id.full_name}}</td>
               <td data-label="Description">{{log.description}}</td>
               <td data-label="Date Created">{{log.created_at}}</td>
            </tr>
            {% endfor %}
            

         </tbody>
         </table>
   </div>

   <div class="btn-dark" id="btnPrintPDF">
   <a><span class="iconify" data-icon="akar-icons:paper" style="color: white;"></span>Print to PDF</a>
   </div>
   {% else %}
   <p class="placeholder-not-found">No logs yet.</p>
   {% endif %}
</div>
</section>

<script>
   
      var fromDateObject, fromDateString;
      var toDateObject, toDateString;

      $("#datepicker-start").datepicker({
         maxDate: 0,
         dateFormat: 'yy-mm-dd',
         onSelect: function(dateText, inst) {
            fromDateObject = $(this).datepicker('getDate'); //the getDate method
            $("#datepicker-end").val("");
            $("#datepicker-end").prop("disabled", false);
            $(".end-date").removeClass("end-date-disabled");
            
            $("#datepicker-end").datepicker("destroy");
            $("#datepicker-end").datepicker({
               minDate: fromDateObject,
               maxDate: new Date(),
               dateFormat: 'yy-mm-dd',
               onSelect: function(dateText, inst) {
                  toDateObject = $(this).datepicker('getDate'); //the getDate method
                  window.location.href = getUrlMask();
               }
            });
         }
      });

      function getUrlForFilter1() {
         fromDateText = $('#datepicker-start').val();
         toDateText = $('#datepicker-end').val();
         console.log(fromDateText);

         if (toDateText == '') {
            const date = new Date();
            var y = date.getFullYear();
            var m = ("0"+(date.getMonth()+1)).slice(-2);
            var d = ("0"+date.getDate()).slice(-2);

            toDateText = y + "-" + m + "-" + d;
         }

         var sort = $("#select-sort").val();

         var url_mask = "{% url 'activity-log:filter1' 222222 'date1' 'date2' %}"
         .replace(/222222/, sort)
         .replace(/date1/, fromDateText)
         .replace(/date2/, toDateText);

         return url_mask;
      }
      
      function getUrlForFilter2() {
      console.log("hello! " + url_mask);
         fromDateText = $('#datepicker-start').val();
         toDateText = $('#datepicker-end').val();
         console.log(fromDateText);

         if (toDateText == '') {
            const date = new Date();
            var y = date.getFullYear();
            var m = ("0"+(date.getMonth()+1)).slice(-2);
            var d = ("0"+date.getDate()).slice(-2);

            toDateText = y + "-" + m + "-" + d;
         }

         var sort = $("#select-sort").val();
         var query = $("#search").val();

         var url_mask = "{% url 'activity-log:filter2' 222222 'date1' 'date2' 'query' %}"
                        .replace(/222222/, sort)
                        .replace(/query/, query)
                        .replace(/date1/, fromDateText)
                        .replace(/date2/, toDateText);

         return url_mask;
      }

      function getUrlMask() {
         var url_mask;

         if ($("#search").val() == '') {
            url_mask = getUrlForFilter1();
         } else {
            url_mask = getUrlForFilter2();
         }

         return url_mask;
      }

      $('#search').keypress(
         function(e){
            if (e.which == 13) {
              window.location.href = getUrlMask();
            }
      });

      $("#select-sort").change(function() {
         window.location.href = getUrlMask();
      });

      $("#btnPrintPDF").click(function() {
         window.location.href = getUrlPrintMask();
      });
    
      function getUrlForPrintFilter1() {
         fromDateText = $('#datepicker-start').val();
         toDateText = $('#datepicker-end').val();
         console.log(fromDateText);

         if (toDateText == '') {
            const date = new Date();
            var y = date.getFullYear();
            var m = ("0"+(date.getMonth()+1)).slice(-2);
            var d = ("0"+date.getDate()).slice(-2);

            toDateText = y + "-" + m + "-" + d;
         }

         var sort = $("#select-sort").val();

         var url_mask = "{% url 'activity-log:printFilter1' 222222 'date1' 'date2' %}"
         .replace(/222222/, sort)
         .replace(/date1/, fromDateText)
         .replace(/date2/, toDateText);

         return url_mask;
      }
      
      function getUrlForPrintFilter2() {
         console.log("hello! " + url_mask);
         fromDateText = $('#datepicker-start').val();
         toDateText = $('#datepicker-end').val();
         console.log(fromDateText);

         if (toDateText == '') {
            const date = new Date();
            var y = date.getFullYear();
            var m = ("0"+(date.getMonth()+1)).slice(-2);
            var d = ("0"+date.getDate()).slice(-2);

            toDateText = y + "-" + m + "-" + d;
         }

         var sort = $("#select-sort").val();
         var query = $("#search").val();

         var url_mask = "{% url 'activity-log:printFilter2' 222222 'date1' 'date2' 'query' %}"
                        .replace(/222222/, sort)
                        .replace(/query/, query)
                        .replace(/date1/, fromDateText)
                        .replace(/date2/, toDateText);

         return url_mask;
      }

      function getUrlPrintMask() {
         var url_mask;

         if ($("#search").val() == '') {
            url_mask = getUrlForPrintFilter1();
         } else {
            url_mask = getUrlForPrintFilter2();
         }

         return url_mask;
      }
</script>

{% endblock %}